version: "3.9"

services:
  flask_app:
    container_name: taskmaster
    image: taskmaster 
    build: .
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - TEST_DB_URL=postgresql://postgres:postgres@flask_test_db:5432/postgres 
    ports: 
      - "5000:5002" 
    depends_on:
      - flask_db
      - flask_test_db 
  flask_db: 
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data
  flask_test_db:
    container_name: flask_test_db
    image: postgres:12 
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
# psql volume 
volumes:
  pgdata: {} 
